### ISSUE TITLE
Signup

### ISSUE THREAD

**Issue by lugodev** [JustShip/justshipto_core#6]
Users sign up with their email & password.

1. User fills the form, including email & password.
2. We email the user, with a temporary code to confirm the email.
3. User types the security code.
4. Account is activated.
5. Core sends the token to frontend.
6. Frontend login with the token.
7. Redirects the user to `/onboarding`.

**Comment by CarlosLugones** [comment]
- [x] Captcha

**Comment by CarlosLugones** [comment]
Done!
