### ISSUE TITLE
Recover password

### ISSUE THREAD

**Issue by lugodev** [JustShip/justshipto_core#9]
User requests password reset.

1. User clicks the "I forgot my password" button.
2. Redirects to `/recover` page.
3. User fills the form with email.
4. Sends the form to the core.
5. Core checks email, if exists, we send a temporary code to the email.
6. Email form in frontend disappears.
7. Temporary code form in frontend appears.
8. User types the temporary code and the new password.
9. New form with code and password is sent to the core.
10. Core checks account with email & temporary code, and sets up the new password, returning a new token.
11. Frontend logs in witht the new token.
12. User is redirected to `/profile`.

**Comment by ragnarok22** [comment]
Para los @JustShip/frontend:
El proceso de recuperar contraseña tiene 4 etapas:

1. la primera vista se muestra un formulario pidiendo el email del usuario
2. una vez enviado el correo se muestra una vista diciendo: se te ha enviado un email, por favor revisa el correo
3. cuando pinche el enlace del correo se muestra una vista diciendo: ingrese su contraseña nueva y un formulario
4. una vez que ponga su contraseña nueva muestra, se ha cambiado su contraseña satisfactoriamente, por favor logueése

**Comment by ragnarok22** [comment]
Para los @JustShip/frontend:
El proceso de recuperar contraseña tiene 4 etapas:

1. la primera vista se muestra un formulario pidiendo el email del usuario
2. una vez enviado el correo se muestra una vista diciendo: se te ha enviado un email, por favor revisa el correo
3. cuando pinche el enlace del correo se muestra una vista diciendo: ingrese su contraseña nueva y un formulario
4. una vez que ponga su contraseña nueva muestra, se ha cambiado su contraseña satisfactoriamente, por favor logueése
